import React, { useEffect, useState } from 'react';
import { ExternalLink, FileText } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { apiRequest } from '../api';

const VerificationReviewPage = () => {
  const { submissionId } = useParams(); const navigate = useNavigate(); const [review, setReview] = useState(null); const [error, setError] = useState(''); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false); const [preview, setPreview] = useState(null);
  useEffect(() => { apiRequest(`/api/admin/verification-submissions/${submissionId}`).then((data) => setReview(data.review)).catch((e) => setError(e.message)); }, [submissionId]);
  const openDocument = async (document) => { try { const data = await apiRequest(`/api/admin/verification-documents/${document.id}/access`, { method: 'POST' }); setPreview({ ...document, url: data.url }); } catch (e) { setError(e.message); } };
  const decide = async (decision) => { if (decision === 'reject' && !reason.trim()) { setError('Enter a rejection reason.'); return; } setBusy(true); setError(''); try { await apiRequest(`/api/admin/verification-submissions/${submissionId}/${decision}`, { method: 'PATCH', body: JSON.stringify({ reason: reason.trim() }) }); navigate('/verification'); } catch (e) { setError(e.message); setBusy(false); } };
  if (error && !review) return <div className="form-error">{error}</div>; if (!review) return <div className="loading-card">Loading submission…</div>;
  const owner = review.owner; const name = review.ownerType === 'Lab' ? owner.labName : owner.clinicName; const email = review.ownerType === 'Lab' ? owner.email : owner.clinicEmail;
  return <><header className="admin-page-head"><div><span className="eyebrow">Verification review · Submission {review.version}</span><h1>{name}</h1><p>{review.ownerType} · {email}</p></div><span className={`status ${review.status.toLowerCase().replaceAll(' ', '-')}`}>{review.status}</span></header>
    {error ? <div className="form-error">{error}</div> : null}<div className="detail-grid"><section className="data-panel"><h2>Organization</h2><dl><dt>PAN/VAT number</dt><dd>{review.panVatNumber}</dd><dt>Location</dt><dd>{owner.location}</dd><dt>Contact</dt><dd>{owner.contactNumber}</dd><dt>Submitted</dt><dd>{new Date(review.submittedAt).toLocaleString()}</dd></dl></section>
      <section className="data-panel"><h2>Documents</h2><div className="document-list">{review.documents.map((document) => <button type="button" key={document.id} onClick={() => openDocument(document)}><FileText /><span><strong>{document.documentType === 'CompanyRegistrationCertificate' ? 'Company registration certificate' : 'PAN/VAT document'}</strong><small>{document.originalFileName}</small></span><ExternalLink size={17} /></button>)}</div></section></div>
    {review.status === 'Under Review' ? <section className="data-panel review-actions"><h2>Decision</h2><label>Rejection reason<textarea value={reason} onChange={(e) => setReason(e.target.value)} maxLength={1000} placeholder="Required only when rejecting" /></label><div><button type="button" className="reject-button" disabled={busy} onClick={() => decide('reject')}>Reject submission</button><button type="button" className="approve-button" disabled={busy} onClick={() => decide('approve')}>Approve verification</button></div></section> : null}
    {preview ? <div className="preview-overlay" role="dialog" aria-label={preview.originalFileName} onClick={() => setPreview(null)}><div className="preview-modal" onClick={(event) => event.stopPropagation()}><header><strong>{preview.originalFileName}</strong><button type="button" onClick={() => setPreview(null)}>Close</button></header>{preview.mimeType === 'application/pdf' ? <iframe title={preview.originalFileName} src={preview.url} referrerPolicy="no-referrer" /> : <img src={preview.url} alt={preview.originalFileName} referrerPolicy="no-referrer" />}</div></div> : null}</>;
};
export default VerificationReviewPage;
